[tools]
"aqua:JohnnyMorganz/StyLua" = "latest"
"aqua:Kampfkarren/selene" = "latest"
"aqua:LuaLS/lua-language-server" = "latest"
"aqua:luau-lang/luau" = "latest"
"github:1Axen/blink" = "latest"
"github:JohnnyMorganz/luau-lsp" = "latest"
"github:JohnnyMorganz/wally-package-types" = "latest"
"github:Roblox/rocale-cli" = "latest"
"github:UpliftGames/wally" = "latest"
"github:anomalyco/opencode" = "latest"
"github:rojo-rbx/rojo" = "latest"
"npm:@openai/codex" = "latest"
"npm:@openchamber/web" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
bun = "latest"
node = "lts"
python = "latest"
rust = { version = "latest", components = "rust-analyzer" }
zig = "latest"
zls = "latest"
