[tools]
node = "lts"
"npm:@openai/codex" = "latest"
rust = "latest"
"npm:bash-language-server" = "latest"
bun = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
