[tools]
"npm:@openai/codex" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
bun = "latest"
node = "lts"
rust = "latest"
"github:anomalyco/opencode" = "latest"
zig = "latest"
zls = "latest"
