#!/bin/bash

options=(
  style=round
  width=2.0
  hidpi=on
  # active_color=0xffbfa8e3 # pink
  active_color=0xffe99b97 # orange
  # active_color=0xffe1e3e4 # white
  inactive_color=0xff4a4d62
)

borders "${options[@]}"
