[[manager.prepend_keymap]]
on = "<C-c>"
run = ["plugin system-clipboard"]

[[manager.prepend_keymap]]
on = "t" # unbind tabs
run  = "plugin max-preview"
desc = "Maximize or restore preview"

[[manager.prepend_keymap]]
on   = [ "c", "a" ]
run  = "plugin compress"
desc = "Archive selected files"
