set-option -g terminal-overrides ',xterm-256color:RGB'

set -g prefix C-Space
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 50000       # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g status-position bottom    # macOS / darwin style
set -g default-terminal "${TERM}"
set -g mouse on
set -g repeat-time 0
set -g mode-style "fg=black,bg=white"
set -g status-justify centre
set -g popup-border-style "fg=red"
set -g popup-border-lines "rounded"

setw -g mode-keys vi

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "tmux load-buffer -w -"

# scroll one line instead of chunks
bind -T copy-mode-vi WheelUpPane send-keys -X scroll-up
bind -T copy-mode-vi WheelDownPane send-keys -X scroll-down

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -r H split-window -hb
bind -r J split-window -v
bind -r K split-window -vb
bind -r L split-window -h

bind -r b switch-client -l

bind -r x kill-pane
bind -r w kill-pane
bind -r t new-window

bind -r U 'copy-mode; send-keys -X halfpage-up'
bind -r D 'copy-mode; send-keys -X halfpage-down'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin '27medkamal/tmux-session-wizard'
set -g @plugin 'wutwere/rose-pine-tmux'
set -g @plugin 'fcsonline/tmux-thumbs'

set -g @session-wizard 'f'
set -g @session-wizard-height 50
set -g @session-wizard-width 50

set -g @continuum-restore 'on'

set -g @thumbs-unique enabled
set -g @thumbs-command 'echo -n {} | tmux load-buffer -w -'

run '~/.tmux/plugins/tpm/tpm'

set -g mode-style "fg=black,bg=white"
